name: Weekly debian rootfs generator

#on:
#  schedule:
#    - cron: '0 0 * * 0'

on: [push]

jobs:
  build:
    strategy:
      matrix:
        target_arch: [armhf, arm64, amd64, i386, riscv64, ppc64el]

    name: Build and upload artifacts
    runs-on: ubuntu-latest
    container: debian:latest

    steps:
      - name: Install dependencies
        run: apt-get update -y && apt-get install debootstrap git xz-utils -y

      - name: Run debootstrap
        run: mkdir -p debian-rootfs && debootstrap --arch=${{matrix.target_arch}} --foreign sid ./debian-rootfs http://deb.debian.org/debian

      - name: Package tarball
        run: tar -Jcvf debian-rootfs-$(date +'%Y%m%d')-${{matrix.target_arch}}.tar.xz debian-rootfs

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: debian-rootfs-${{matrix.target_arch}}
          path: debian-rootfs-*.tar.xz

  upload:
    name: Upload artifacts
    needs: build
    runs-on: ubuntu-latest
    container: debian:latest

    steps:
      - name: Install dependencies
        run: apt-get update -y && apt-get install debootstrap git xz-utils -y

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Git config
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Create release tag
        run: |
          git config user.name 'mintsuki'
          git config user.email 'mintsuki@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/mintsuki/debian-rootfs.git
          git fetch --all
          git commit --allow-empty -m "Debian rootfs $(date +'%Y%m%d') [ci skip]"
          git push origin trunk
          git tag rootfs-$(date +'%Y%m%d')
          git push origin trunk --tags

      - name: Get date
        run: echo "build_date=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: rootfs-${{ env.build_date }}
          files: |
            debian-rootfs-*.tar.xz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
